name: Free RDP By GitHub Actions
on: 
  workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup RDP
        run: |
          cmd /c echo off
          cmd /c net user admin1 RDPpassword /add
          cmd /c net localgroup Administrators admin1 /add
          cmd /c reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          cmd /c reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService" /v Start /t REG_DWORD /d 2 /f
          cmd /c netsh advfirewall firewall set rule group="Remote Desktop" new enable=Yes
          cmd /c wmic computersystem where name="%computername%" call rename name="MyRDP"
          cmd /c wmic useraccount where name='admin1' set PasswordExpires=False
      - name: Get IP
        run: |
          curl ifconfig.me
          
